version: 2
updates:
  - package-ecosystem: bundler
    directory: /ruby/engine
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
